#! /bin/sh
pkill -f "bspc subscribe monitor"
pgrep -x sxhkd > /dev/null || sxhkd &

# Check number of connected minitors and set right setup
set_desktops() {
	if [ "$#" -eq 1 ]; then
		bspc monitor "$1" -d 1 7 8 9 10 2 3 4 5 6
	else
		bspc monitor "$1" -d 1 7 8 9 10
		xrandr --output "$1" \
		       --primary --mode 1920x1080 --rotate normal \
		       --output "$2" \
		       --mode 1920x1080 --rotate normal \
		       --right-of "$1"
		bspc monitor "$2" -d 2 3 4 5 6
	fi
}

init() {
	monitors=($(xrandr --query | awk '/ connected / {print $1}'))
	set_desktops "${monitors[@]}"
}

bspc subscribe monitor | while read -r event; do
	init
done &

# Entrypoint
init

# Wallpaper
feh --bg-fill ~/Wallpapers/Mocha_Wolf.png

# Set color scheme skipping terminal and tty
wal --cols16 -i ~/Wallpapers/Mocha_Wolf.png -s -t

# Source pywal16 colors
. "${HOME}/.cache/wal/colors.sh"

~/.config/polybar/launch.sh &	

bspc config border_width        1
bspc config window_gap          10
bspc config top_padding		    -10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Rules
# bspc rule -a Slack desktop='7'
bspc rule -a teams-for-linux desktop='7'
bspc rule -a Alacritty desktop='1'
bscp rule -a Mail desktop='9'

# Border old
# bspc config focused_border_color    "#82cfff"
# bspc config normal_border_color     "#1e1e2e"
# bspc config active_border_color     "#1e1e2e"
# bspc config presel_feedback_color	"#008ce3"
# Border pywal16
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Path to the autostart flag file
AUTOSTART_FLAG="/tmp/bspwm_autostart_done"

# Start applications only if not already started
if [ ! -f "$AUTOSTART_FLAG" ]; then
    touch "$AUTOSTART_FLAG"

    # Bar
    # Compositor
    # picom --experimental-backends &
    picom &
    # Notifications
    killall -9 dunst && /usr/bin/dunst &
    # Polkit
    #/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    # Dex
    #dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
    # Network Applet
    nm-applet --indicator &
    # Cursor
    xsetroot -cursor_name left_ptr &
    # Low battery notifier
    ~/.config/bspwm/scripts/low_bat_notifier.sh &

    # Autostart programs
    alacritty &
    google-chrome &
    # slack &
    teams-for-linux &
    thunderbird &
    #alacritty -e $SHELL -c "make stand-up && exec $SHELL" &  

    setxkbmap -layout us
    setxkbmap -option compose:ralt
fi
