#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Check number of connected minitors and set right setup
set_desktops() {
	if [ "$#" -eq 1 ]; then
		bspc monitor "$1" -d 1 2 3 4 5 6 7 8 9 10
	else
		bspc monitor "$1" -d 1 7 8 9 10
		xrandr --output "$1" \
		       --primary --mode 1920x1080 --rotate normal \
		       --output "$2" \
		       --mode 1920x1080 --rotate normal \
		       --right-of "$1"
		bspc monitor "$2" -d 2 3 4 5 6
	fi
}

init() {
	monitors=($(xrandr --query | awk '/ connected / {print $1}'))
	set_desktops "${monitors[@]}"
}

bspc subscribe monitor | while read -r event; do
	init
done &

# Entrypoint
init	

bspc config border_width        1
bspc config window_gap          10
bspc config top_padding		    -5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Rules
bspc rule -a Slack desktop='7'
# bspc rule -a Google-chrome desktop='2'
bspc rule -a Alacritty desktop='1'
bscp rule -a Thunderbird desktop='9'

# Border
bspc config focused_border_color    "#82cfff"
bspc config normal_border_color     "#1e1e2e"
bspc config active_border_color     "#1e1e2e"
bspc config presel_feedback_color	"#008ce3"


# Autostart

# Bar
~/.config/polybar/launch.sh &
# Compositor
picom --experimental-backend &
# Notifications
killall -9 dunst && /usr/bin/dunst &
# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill ~/Wallpapers/wallpaper.jpg
# Dex
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Autostart programs
alacritty &
google-chrome &
slack &
thunderbird &
#alacritty -e $SHELL -c "make stand-up && exec $SHELL" &  

setxkbmap -layout us
setxkbmap -option compose:ralt
